version: 2
updates:
  # Mobile app dependencies
  - package-ecosystem: "npm"
    directory: "/apps/mobile"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "America/New_York"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
    reviewers:
      - "NoiseMeldOrg/developers"
    assignees:
      - "NoiseMeldOrg/developers"
    labels:
      - "dependencies"
      - "mobile"
    commit-message:
      prefix: "chore(mobile)"
      include: "scope"

  # Admin app dependencies  
  - package-ecosystem: "npm"
    directory: "/apps/admin"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "05:00"
      timezone: "America/New_York"
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
    reviewers:
      - "NoiseMeldOrg/developers"
    assignees:
      - "NoiseMeldOrg/developers" 
    labels:
      - "dependencies"
      - "admin"
    commit-message:
      prefix: "chore(admin)"
      include: "scope"

  # GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00" 
      timezone: "America/New_York"
    reviewers:
      - "NoiseMeldOrg/developers"
    assignees:
      - "NoiseMeldOrg/developers"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(ci)"
      include: "scope"