services:
  - type: web
    name: coach-meld-admin
    runtime: node
    region: oregon # Change to your preferred region
    plan: starter # Change to 'standard' for production
    rootDir: apps/admin
    buildCommand: cd ../.. && npm install && npm run build:packages && cd apps/admin && npm run build
    startCommand: NODE_ENV=production npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false # Set in Render dashboard
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false # Set in Render dashboard
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false # Set in Render dashboard
      - key: GEMINI_API_KEY
        sync: false # Set in Render dashboard
      - key: PORT
        value: 3000
    autoDeploy: true # Automatically deploy on push to main
    branch: main # Fixed to use main branch