# Dependabot configuration for coach-meld-admin
# This configuration reduces noise from dependabot while keeping security updates

version: 2
updates:
  # npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      # Check for updates once a week on Monday
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    
    # Group minor and patch updates together to reduce PR noise
    groups:
      minor-and-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    
    # Ignore major version updates for critical packages that often have breaking changes
    ignore:
      # Tailwind CSS 4 has breaking changes incompatible with shadcn/ui
      - dependency-name: "tailwindcss"
        versions: ["4.x", "5.x"]
      
      # Next.js major versions often require migration work
      - dependency-name: "next"
        update-types: ["version-update:semver-major"]
      
      # React major versions require careful migration
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      
      # Supabase major versions may have API changes
      - dependency-name: "@supabase/supabase-js"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@supabase/ssr"
        update-types: ["version-update:semver-major"]
      
      # TypeScript major versions can introduce new strictness
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]
      
      # ESLint major versions often have config changes
      - dependency-name: "eslint"
        update-types: ["version-update:semver-major"]
      - dependency-name: "eslint-config-next"
        update-types: ["version-update:semver-major"]
    
    # Limit the number of open PRs
    open-pull-requests-limit: 5
    
    # Labels to add to PRs
    labels:
      - "dependencies"
      - "automated"
    
    # Commit message configuration
    commit-message:
      prefix: "chore"
      include: "scope"

  # GitHub Actions dependencies (if you add any workflows later)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    groups:
      actions:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"