services:
  - type: static_site
    name: coachmeld-web
    runtime: node
    region: oregon
    plan: starter # Change to 'standard' for production
    buildCommand: cd apps/mobile && npm ci && npm run build:web
    staticPublishPath: ./apps/mobile/dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: EXPO_PUBLIC_SUPABASE_URL
        sync: false # Set in Render dashboard
      - key: EXPO_PUBLIC_SUPABASE_ANON_KEY
        sync: false # Set in Render dashboard
      - key: EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY
        sync: false # Set in Render dashboard
      - key: EXPO_PUBLIC_STRIPE_MONTHLY_PRICE_ID
        sync: false # Set in Render dashboard
      - key: EXPO_PUBLIC_STRIPE_ANNUAL_PRICE_ID
        sync: false # Set in Render dashboard
      - key: GEMINI_API_KEY
        sync: false # Set in Render dashboard
      - key: SUPABASE_SERVICE_KEY
        sync: false # Set in Render dashboard
      - key: NEXT_PUBLIC_POSTHOG_KEY
        sync: false # Set in Render dashboard (if using analytics)
      - key: NEXT_PUBLIC_POSTHOG_HOST
        sync: false # Set in Render dashboard (if using analytics)
      - key: PUBLIC_SITE_URL
        value: https://coachmeld.app
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        headers:
          X-Frame-Options: DENY
          X-Content-Type-Options: nosniff
          Referrer-Policy: strict-origin-when-cross-origin
    autoDeploy: true
    branch: main