version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    open-pull-requests-limit: 3
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    # Separate group for major updates so they're more visible
    allow:
      - dependency-type: "all"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Higher priority for security updates
    priority: 1

  # Keep GitHub Actions up to date (if CoachMeld uses them)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"